networks:
  reverse-proxy:
    external: true

services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      MY_DOMAIN: ${MY_DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [reverse-proxy]

volumes:
  caddy_data: {}
  caddy_config: {}
