# Headscale listens plain HTTP inside Docker; Caddy does TLS in front.
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

# Keys (files will be created here if missing)
private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# REQUIRED address pools for tailnet IPs (use Tailscale-supported ranges)
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

# DNS: you want override + sane global resolvers
dns:
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8

# SQLite DB on the data volume
database:
  type: sqlite
sqlite:
  path: /var/lib/headscale/db.sqlite
  write_ahead_log: true

# Logging
log:
  level: info
  format: text
