listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

# Legacy WireGuard server key (headscale will create it if missing)
private_key_path: /var/lib/headscale/private.key

# Required for the TS2021 “Noise” protocol (headscale will create it if missing)
noise:
  private_key_path: /var/lib/headscale/noise_private.key

dns:
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
