networks:
  reverse-proxy:
    driver: bridge
  edge:
    external: true
    
services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      BASE_DOMAIN: ${BASE_DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [edge, reverse-proxy]

volumes:
  caddy_data: {}
  caddy_config: {}
