networks:
  omada:

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    networks:
      - omada
    environment:
      TZ: Europe/Vilnius
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
  