networks:
  omada:
    external: true

services:
  omada:
    image: mbentley/omada-controller:latest
    container_name: omada
    restart: unless-stopped
    networks:
      - omada
    environment:
      TZ: ${TZ}
    volumes:
      - ./data:/opt/tplink/EAPController/data
      - ./logs:/opt/tplink/EAPController/logs
      - ./work:/opt/tplink/EAPController/work
    ports:
      - "8043:8043"        # HTTPS UI
      - "8088:8088"        # HTTP UI
      - "8843:8843"        # Guest portal (optional)
      - "29810:29810/udp"  # Discovery
      - "29811:29811"      # v4 mgmt (some devices/firmware still use)
      - "29812:29812"      # v4 adoption
      - "29813:29813"      # v4 upgrade
      - "29814:29814"      # v5 mgmt
      - "29815:29815"      # v5 stats upload
      - "29816:29816"      # v5 remote term