networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
  edge:
    driver: bridge

services:
  traefik:
    image: traefik:v3.5
    restart: unless-stopped
    command:
      - --providers.file.filename=/etc/traefik/infra.tmpl.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    volumes:
      - ./templates/infra.tmpl.yml:/etc/traefik/infra.tmpl.yml:ro
    networks: [edge]

  caddy-infra:
    build: .
    environment:
      BASE_DOMAIN: ${BASE_DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_infra_data:/data
      - caddy_infra_config:/config
    networks: [edge, reverse-proxy]
    depends_on:
      - traefik

volumes:
  caddy_infra_data: {}
  caddy_infra_config: {}
